name: Release

on:
  release:
    types: [published]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/monkesto
  VERSION: ${{ github.ref_name }}

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build amd64 image
        run: docker build -f Dockerfile -t $IMAGE_NAME:${VERSION}-amd64 --push .

  build-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build arm64 image
        run: docker build -f Dockerfile -t $IMAGE_NAME:${VERSION}-arm64 --push .

  merge_manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create $IMAGE_NAME:${VERSION} \
            --amend $IMAGE_NAME:${VERSION}-amd64 \
            --amend $IMAGE_NAME:${VERSION}-arm64

          docker manifest annotate $IMAGE_NAME:${VERSION} $IMAGE_NAME:${VERSION}-amd64 --arch amd64
          docker manifest annotate $IMAGE_NAME:${VERSION} $IMAGE_NAME:${VERSION}-arm64 --arch arm64

          docker manifest push $IMAGE_NAME:${VERSION}

          docker manifest create $IMAGE_NAME:latest \
            --amend $IMAGE_NAME:${VERSION}-amd64 \
            --amend $IMAGE_NAME:${VERSION}-arm64

          docker manifest push $IMAGE_NAME:latest
