name: Build and Publish docker image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image
        run: COMPOSE_PROJECT_NAME=double-book docker compose build app

      - name: Generate version number
        id: ver
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Tag image with release version
        run: |
          docker tag double-book-app:latest ghcr.io/${{ github.repository_owner }}/double-book:${{ steps.ver.outputs.VERSION }}

      - name: Tag image as latest
        run: |
          docker tag double-book-app:latest ghcr.io/${{ github.repository_owner }}/double-book:latest

      - name: Push tags to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/double-book:${{ steps.ver.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/double-book:latest
